name: release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install Dependencies
      run: pnpm install
    - name: Build
      run: pnpm build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install Dependencies
      run: pnpm install
    - name: Test Services
      run: pnpm test:services:start
    - name: Build
      run: pnpm build
    - name: Testing
      run: pnpm test:ci

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install Dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
    - name: Publish
      run: pnpm publish --provenance --no-git-checks
